import type { Metadata, Viewport } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

// Inter for everything — matches jawaadahmar.com landing-page typography.
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// `--font-serif` is intentionally aliased to Inter so the legacy
// `font-heading` utility still resolves to a real font without pulling in a
// separate serif family.
// Absolute origin for OG/Twitter image URLs + auth email links. Set
// NEXT_PUBLIC_SITE_URL in production; the browser origin is used locally.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "House of Ahmar",
    template: "%s · House of Ahmar",
  },
  description:
    "A private home for the House of Ahmar — our people, our gatherings, our story. By initiation only.",
  applicationName: "House of Ahmar",
  appleWebApp: {
    capable: true,
    title: "House of Ahmar",
    statusBarStyle: "black-translucent",
  },
  // Static assets in /public (generated by scripts/generate-icons.mjs).
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon.png", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: "House of Ahmar",
    title: "House of Ahmar",
    description: "A private home for our family. By initiation only.",
    images: [
      { url: "/og-image.png", width: 1200, height: 630, alt: "House of Ahmar" },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "House of Ahmar",
    description: "A private home for our family. By initiation only.",
    images: ["/og-image.png"],
  },
  // Private space — keep it out of search engines entirely.
  robots: {
    index: false,
    follow: false,
    googleBot: { index: false, follow: false },
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} ${inter.className} ${geistMono.variable} antialiased`}
        style={{ ["--font-serif" as string]: "var(--font-sans)" }}
      >
        <TooltipProvider>
          {children}
          <Toaster
            position="top-center"
            closeButton
            theme="dark"
            toastOptions={{
              style: {
                background: "#0a0a0a",
                border: "1px solid #262626",
                color: "#ededed",
              },
            }}
          />
        </TooltipProvider>
      </body>
    </html>
  );
}
