import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import "@fontsource-variable/inter";
import "@fontsource-variable/geist-mono";

// `--font-serif` is intentionally aliased to Inter so the legacy
// `font-heading` utility still resolves to a real font without pulling in a
// separate serif family.
// Absolute origin for OG/Twitter image URLs + auth email links. Prefer an
// explicit NEXT_PUBLIC_SITE_URL, fall back to the Vercel deploy URL, then local.
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL}`
    : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "House of Ahmar",
    template: "%s · House of Ahmar",
  },
  description:
    "A private home for the House of Ahmar — our people, our gatherings, our story.",
  applicationName: "House of Ahmar",
  appleWebApp: {
    capable: true,
    title: "House of Ahmar",
    statusBarStyle: "black-translucent",
  },
  // Static assets in /public (generated by scripts/generate-icons.mjs).
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon.png", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: "House of Ahmar",
    title: "House of Ahmar",
    description: "A private home for our family.",
    images: [
      { url: "/og-image.png", width: 1200, height: 630, alt: "House of Ahmar" },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "House of Ahmar",
    description: "A private home for our family.",
    images: ["/og-image.png"],
  },
  // Private space — keep it out of search engines entirely.
  robots: {
    index: false,
    follow: false,
    googleBot: { index: false, follow: false },
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  colorScheme: "dark",
  // Required for `env(safe-area-inset-*)` to return anything but 0px. Without
  // it the bottom-nav and layout padding that compensate for the iPhone home
  // indicator are dead code, and the installed PWA (manifest `standalone` +
  // `black-translucent` status bar) renders the tab bar underneath it.
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className="font-sans antialiased"
        style={{
          ["--font-sans" as string]: '"Inter Variable", sans-serif',
          ["--font-serif" as string]: '"Inter Variable", sans-serif',
          ["--font-geist-mono" as string]: '"Geist Mono Variable", monospace',
        }}
      >
        <TooltipProvider>
          {children}
          <Toaster
            position="top-center"
            closeButton
            theme="dark"
            toastOptions={{
              style: {
                background: "#0a0a0a",
                border: "1px solid #262626",
                color: "#ededed",
              },
            }}
          />
        </TooltipProvider>
      </body>
    </html>
  );
}
