import type { MetadataRoute } from "next";

// PWA manifest — makes "Add to Home Screen" render as a real app on phones.
// Icons in /public generated by scripts/generate-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "House of Ahmar",
    short_name: "Ahmar",
    description: "A private home for the House of Ahmar. By initiation only.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      {
        src: "/web-app-manifest-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/web-app-manifest-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
